# Generated by Django 3.1.4 on 2020-12-02 11:49

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addedvideo',
            name='code',
            field=models.CharField(default=home.models.generate_unique_code, max_length=12, null=True, unique=True),
        ),
    ]
